parser: babel-eslint
env:
  browser: true
  es6: true
extends:
  - airbnb
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:jsx-a11y/recommended
  - plugin:sonarjs/recommended
  - plugin:promise/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - jsx-a11y
  - optimize-regex
  - sonarjs
  - no-loops
  - no-use-extend-native
  - promise
rules: {
  "react/jsx-filename-extension": "off",
  "jsx-a11y/click-events-have-key-events": "off",
  "allowTernary": true,
  "optimize-regex/optimize-regex": "warn",
  "sonarjs/cognitive-complexity": ["error", 30],
  "no-loops/no-loops": 2,
  "no-use-extend-native/no-use-extend-native": 2,
}
